### ISSUE TITLE
I have an issue with the name, not awesome enough :-p

### ISSUE THREAD

**Issue by amitu** [xypnox/commit_manager#1]
Maybe gitbox, like git + dropbox. Or gitdrive. 

I am so glad commit+push in background every 10 mins is catching on :-)

**Comment by xypnox** [comment]
> “What's in a name? that which we call a rose
> By any other name would smell as sweet.”
> ― William Shakespeare, Romeo and Juliet

I didn't want to overhype it with a fancier name. I use this script for personal repos and don't want to actively handle or expand it beyond anything that I may need at the moment.
